[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = false

[[redirects]]
  from = "/*"
  to = "https://yuki-lab.com/:splat"
  status = 301
  force = true
  conditions = { Host = "yuki-gh-portfolio.netlify.app" }
